GestionPersonnel/GesPerson/urls.py
from django.urls import path
from . import views
app_name='GesPerson'
urlpatterns = [ 
               path("accueil/",views.index,name='index'),
               path("add_person/",views.add_person,name='add_person'),
               path('add_teacher/',views.add_teacher, name='add_teacher'),
               path('add_student/',views.add_student, name='add_student'),
               path('teacher/', views.teacher_list, name='teacher_list'),
               path('student/', views.student_list, name='student_list'),
               path('teacher/update/<int:teacher_id>/',views.update_teacher, name='update_teacher'),
               path('student/update/<int:student_id>/',views.update_student, name='update_student'),
               path('display_person/', views.display_person, name='display_person'),
        ]

GestionPersonnel/GestionPersonnel/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('GesPerson/', include('GesPerson.urls')),
]

GestionPersonnel/GesPerson/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    first_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50)
    birth_date=models.DateField()
    tel=models.IntegerField()
    email= models.EmailField(max_length=50)
    
    
    class Meta :
        abstract =True
    
    def __str__(self) -> str:
        return self.first_name + " "+ self.last_name +" " + str(self.tel) +" "+self.birth_date
        
        
class Teacher (Person) :
    speciality=models.CharField( max_length=50)

class Student(Person):
    pathway=models.CharField(max_length=50)

GestionPersonnel/GesPerson/forms.py
from django import forms
from GesPerson.models import *
#Avec la classe Form , d'apres mes recherche dans la documentation, j'ai pas trouvée la methode de form pour enregistrer les données du formulaire
# class TeacherForm(forms.Form):
#       first_name=forms.CharField(label="first_name",max_length=50, required=True)
#       last_name=forms.CharField(label="Last Name", max_length=50, required=True)
#       birth_date=forms.DateField(label="Birthday Date", required=True)
#       tel=forms.IntegerField(label="Phone Number", required=False)
#       email=forms.EmailField(label="E-mail", required=False)
#       speciality=forms.CharField(label="Speciality", max_length=50, required=False)
      
      
class TeacherForm(forms.ModelForm):
    class Meta :
        model=Teacher
        fields="__all__"
        
    def clean(self):
        
        cleaned_data = super().clean()
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if not first_name.isalpha():
       
            raise forms.ValidationError("le champs first_name n'accepte pas les caractères numériques.")
        if not last_name.isalpha():
            raise forms.ValidationError("le champs last_name n'accepte pas les caractères numériques.")
        

        return cleaned_data
    
class StudentForm(forms.ModelForm):
    class Meta :
        model=Student
        fields="__all__"
        
    def clean(self):
        
        cleaned_data = super().clean()
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if not first_name.isalpha():
       
            raise forms.ValidationError("le champs first_name  n'accepte pas les caractères numériques.")
        if not last_name.isalpha():
            raise forms.ValidationError("le champs last_name  n'accepte pas les caractères numériques.")
        

        return cleaned_data

GestionPersonnel/GesPerson/views.py
from django.shortcuts import render ,redirect,get_object_or_404,reverse
from django.http import HttpResponse
from .models import *
from .forms import *
# Create your views here.

def index(request):

    return  render(request,'index.html', {})



def add_person(request):
    return render(request,'add_person.html', locals())

#########################""view de teacher
def add_teacher(request):
    if request.method == 'POST':
        form = TeacherForm(request.POST)
        print(form.is_valid())
        if form.is_valid():
            form.cleaned_data
            form.save()
           
            return redirect('GesPerson:teacher_list') 
    else:
        form = TeacherForm()

    return render(request,'teachers/add_teacher.html', {'form': form})


def teacher_list(request):
    teachers= Teacher.objects.all()
    return render(request,'teachers/teacher_list.html', locals())

def update_teacher(request, teacher_id):
    teacher = get_object_or_404(Teacher, id=teacher_id)

    if request.method == 'POST':
        form = TeacherForm(request.POST, instance=teacher)
        if form.is_valid():
            form.save()
            return redirect(reverse('GesPerson:teacher_list'))
    else:
        form = TeacherForm(instance=teacher)

    return render(request, 'teachers/teacher_update.html', locals())


#################view students
def add_student(request):
    if request.method == 'POST':
      
        form = StudentForm(request.POST)
        
        if form.is_valid():
           
            form.save()
            return redirect('GesPerson:student_list')  
    else:
     
        form = StudentForm()

    return render(request, 'students/add_student.html', {'form': form})


def student_list(request):
    students= Student.objects.all()
    return render(request,'students/student_list.html', locals())

##update for student
def update_student(request,  student_id):
    student= get_object_or_404(Student, id=student_id)

    if request.method == 'POST':
        form = StudentForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return redirect(reverse('GesPerson:student_list'))
    else:
        form = StudentForm(instance=student)

    return render(request, 'students/student_update.html', locals())


####
def display_person(request):
      
      return render(request,'display_person.html', locals())
    

GestionPersonnel/GesPerson/templates/add_person.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Gestion</title>
</head>
<body>
  <ul>
    <li><a href="{% url 'GesPerson:add_teacher' %}">Add Teacher</a></li>
    <li><a href="{% url 'GesPerson:add_student' %}">Add Studient</a></li>
  </ul>
  
</body>
</html>

GestionPersonnel/GesPerson/templates/display_person.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'gesperson:teacher_list' %}">Add Teacher</a>
    <a href="{% url 'gesperson:student_list' %}">Add Student</a>
   
</body>
</html>

GestionPersonnel/GesPerson/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Gestion Personnel</title>

  <!-- Inclure Bootstrap (avec la CDN) -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Votre École</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="#">Accueil <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          {% comment %} <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" class="svg-icon"><path d="M2 2v26h30V2H2zm14 7.999h6V14h-6V9.999zM16 16h6v4h-6v-4zm-2 10H4v-4h10v4zm0-6H4v-4h10v4zm0-6H4V9.999h10V14zm2 12v-4h6v4h-6zm14 0h-6v-4h6v4zm0-6h-6v-4h6v4zm0-6h-6V9.999h6V14z"/></svg> {% endcomment %}
          <a class="nav-link" href="{% url 'GesPerson:teacher_list' %}">Liste Eleves</a>
        </li>
        <li class="nav-item">
          <a  class="nav-link" href="{% url 'GesPerson:student_list' %}">Liste  student</a>

        </li>
        <li class="nav-item">
          <a  class="nav-link" href="{% url 'GesPerson:add_teacher' %}">ajouter teacher</a>
        </li>
        <li class="nav-item">
          <a  class="nav-link" href="{% url 'GesPerson:add_student' %}">ajouter student</a> 
        </li> 
      </ul>
    </div>

    <!-- Ajouter un bouton de connexion/déconnexion -->
   
  </nav>

  <!-- Le reste de votre contenu ici -->

  <!-- Inclure Bootstrap JS (avec la CDN) -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

GestionPersonnel/GesPerson/templates/students/add_student.html
<h2 class="mb-4">Enregistrer un etudiant</h2>
<button><a href="{% url 'GesPerson:student_list' %}">Students List </a></button><br><br>
<form method="POST" action="{% url 'GesPerson:add_student' %}">
  {% csrf_token %}
  
  <!-- Display error messages -->
  {% if form.non_field_errors %}
    <p class="error">{{ form.non_field_errors }}</p>
  {% endif %}

  {{ form.first_name.label_tag }} {{ form.first_name }} <br><br>
  {{ form.last_name.label_tag }} {{ form.last_name }} <br><br>
  {{ form.birth_date.label_tag }} {{ form.birth_date }} <br><br>
  {{ form.tel.label_tag }} {{ form.tel }} <br><br>
  {{ form.email.label_tag }} {{ form.email }} <br><br>
  {{ form.pathway.label_tag }} {{ form.pathway }} <br> <br>

  <button type="submit">Enregistrer</button>
</form>

GestionPersonnel/GesPerson/templates/students/student_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Gestion</title>
</head>
<body>

  <h2>Liste des students</h2>
  <table border="2">
    <thead>
      <tr>
        <th>ID</th>
        <th>FirlstName</th>
        <th>LasteName</th>
        <th>last_name</th>
        <th> pathway</th>
        
        <th>Action</th>
      </tr>
    </thead>
    <tbody>

      {% for elt in  students %}
      <tr>
        <td>{{elt.id}}</td>
        <td>{{elt.first_name}}</td>
        <td>{{elt.last_name}}</td>
        <td>{{elt.birth_date}}</td>
        <td>{{elt.pathway}}</td>
       
        <td>
          <button><a href="{% url 'GesPerson:update_student' student_id=elt.id %}">Editer</a></button>
          
        </td>
      </tr>
      {% endfor %} 

     
    </tbody>
  </table>

 
</body>
</html>

GestionPersonnel/GesPerson/templates/students/student_update.html
<form method="post" action="{% url 'GesPerson:update_student' student_id=student.id %}">
    {% csrf_token %}
    
    {{ form.as_p }}
    
    <button type="submit">Enregistrer les modifications</button>
  </form>
  

GestionPersonnel/GesPerson/templates/teachers/add_teacher.html
<h2 class="mb-4">Enregistrer un Teacher</h2>
<button><a href="{% url 'GesPerson:teacher_list' %}">Teachers List </a></button><br><br>

<form method="POST" action="{% url 'GesPerson:add_teacher' %}">
  {% csrf_token %}
  

  {% if form.non_field_errors %}
    <p class="error">{{ form.non_field_errors }}</p>
  {% endif %}

  {{ form.first_name.label_tag }} {{ form.first_name }} <br><br>
  {{ form.last_name.label_tag }} {{ form.last_name }} <br><br>
  {{ form.birth_date.label_tag }} {{ form.birth_date }} <br><br>
  {{ form.tel.label_tag }} {{ form.tel }} <br><br>
  {{ form.email.label_tag }} {{ form.email }} <br><br>
  {{ form.speciality.label_tag }} {{ form.speciality }} <br><br>

  <button type="submit">Enregistrer</button>
</form>

GestionPersonnel/GesPerson/templates/teachers/teacher_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Tableau des Enseignants</title>
</head>
<body>
    <button><a href="{% url 'GesPerson:add_teacher' %}">Add teacher </a></button><br><br>
<table border="1">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Birthday Date</th>
            <th>Tel</th>
            <th>Speciality</th>
            <th>Editer</th>
        </tr>
    </thead>
    <tbody>
        {% for teacher in teachers %}
        <tr>
            
            <td>{{ teacher.first_name }}</td>
            <td>{{ teacher.last_name }}</td>
            <td>{{ teacher.email }}</td>
            <td>{{ teacher.birth_date }}</td>
            <td>{{ teacher.tel }}</td>
            <td>{{ teacher.speciality }}</td>
            <td> <button><a href="{% url 'GesPerson:update_teacher' teacher_id=teacher.id %}">Editer</a></button></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

</body>
</html>

GestionPersonnel/GesPerson/templates/teachers/teacher_update.html
<form method="post" action="{% url 'gesperson:update_teacher' teacher_id=teacher.id %}">
    {% csrf_token %}
    
    {{ form.as_p }}
    
    <button type="submit">Enregistrer</button>
  </form>
  